version: '3.3'

volumes:
  db: {}

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ~/workspace/movies/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/workspace/movies/app/web:/opt/server
    links:
      - movies
  movies:
    image: movies
    ports:
      - 9000:9000
    volumes:
      - ~/workspace/movies:/opt/server
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: 123qweasd
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql