version: '3.3'

volumes:
  db: {}
  php-data: {}
  static: {}
  nginx: {}

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - nginx:/etc/nginx/conf.d
      - static:/opt/server
    links:
      - movies
  movies:
    image: finfx/movies:latest
    ports:
      - 9000:9000
    volumes:
      - php-data:/opt/server
      - static:/opt/server/app/web
      - nginx:/opt/server/docker/nginx
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: 123qweasd
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql